spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/notification_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
    username: root
    password: Suresh@7873
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest




  mail:
    host: smtp.gmail.com
    port: 587
    username: beherarajesh93480@gmail.com
    password: bymrqyyozutrrokw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true




server:
  port: 7878



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true